name: Nightlies

on:
  push:
    branches:
      - master

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # load full history
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: install node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build a bot
        run: make

      - name: Zip a bot
        run: make pack

      - uses: actions/upload-artifact@v2
        with:
          name: sogeBot-${{ steps.slug.outputs.sha8 }}
          path: ${{ github.workspace }}/*.zip

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Build & Push to GitHub Package with shasum
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: ${{ secrets.GIT_REPO }}
          TAG_NAME: nightly:${{ github.sha }}
      - name: Build & Push to GitHub Package as latest
        uses: opspresso/action-docker@v0.2.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REGISTRY: docker.pkg.github.com
          IMAGE_NAME: ${{ secrets.GIT_REPO }}
          TAG_NAME: nightly:latest
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@v0.2.8
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY_IMAGE_NIGHTLY }}
          TAG_NAME: ${{ github.sha }}
          LATEST: "true"
